export const SET_QUANTITY_CART = 'SET_QUANTITY_CART';
export const SET_SHOW_MODAL = 'SET_SHOW_MODAL';
export const SET_SHOW_MODAL_EDIT = 'SET_SHOW_MODAL_EDIT';
export const SET_SHOW_MODAL_EDIT_ORDER = 'SET_SHOW_MODAL_EDIT_ORDER';
export const SET_ACTIVE = 'SET_ACTIVE';
export const SET_ID_EDIT = 'SET_ID_EDIT';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_REFRESH_TOKEN = 'SET_REFRESH_TOKEN';